#!/usr/bin/env python3
"""Regenerate js/hb-docs.js from harfbuzz's docs/harfbuzz-sections.txt.

Usage:
  scripts/gen-hb-docs.py [PATH_TO_harfbuzz-sections.txt]

If no path is given, the script auto-detects the HarfBuzz source
tree the same way scripts/build.sh does: $HB_SRC, then
./harfbuzz/ next to this repo, then ~/harfbuzz.
"""
import os
import re
import sys

HERE = os.path.dirname (os.path.dirname (os.path.abspath (__file__)))


def find_sections_txt ():
    env = os.environ.get ("HB_SRC")
    candidates = []
    if env:
        candidates.append (os.path.join (env, "docs", "harfbuzz-sections.txt"))
    candidates.append (os.path.join (HERE, "harfbuzz", "docs", "harfbuzz-sections.txt"))
    candidates.append (os.path.expanduser ("~/harfbuzz/docs/harfbuzz-sections.txt"))
    for c in candidates:
        if os.path.isfile (c):
            return c
    return None


def parse (path):
    """Yield (symbol, section) pairs.

    Section is the <FILE>hb-xxx</FILE> value with the leading
    'hb-' stripped, matching the URL pattern the website uses:
    https://harfbuzz.github.io/harfbuzz-hb-<section>.html.
    """
    section = None
    with open (path, "r", encoding = "utf-8") as f:
        for raw in f:
            line = raw.strip ()
            if not line:
                continue
            m = re.match (r"<FILE>(.+?)</FILE>", line)
            if m:
                name = m.group (1)
                section = name[3:] if name.startswith ("hb-") else name
                continue
            if line.startswith ("<") and line.endswith (">"):
                # <SECTION>, </SECTION>, <SUBSECTION ...>, <TITLE>...
                if line.startswith ("<TITLE>"):
                    continue
                if line.startswith ("</SECTION>"):
                    section = None
                continue
            if section is None:
                continue
            if re.match (r"^(hb_|HB_)[A-Za-z0-9_]*$", line):
                yield line, section


def main (argv):
    if len (argv) > 2:
        print (__doc__, file = sys.stderr)
        return 2
    sections_txt = argv[1] if len (argv) == 2 else find_sections_txt ()
    if not sections_txt or not os.path.isfile (sections_txt):
        print ("error: cannot find harfbuzz-sections.txt", file = sys.stderr)
        print ("       set HB_SRC=/path/to/harfbuzz or pass the path", file = sys.stderr)
        return 1

    pairs = list (parse (sections_txt))
    # Keep first occurrence of each symbol; sections.txt has none
    # in practice, but guard against accidental duplicates.
    seen = {}
    for name, section in pairs:
        seen.setdefault (name, section)

    out_path = os.path.join (HERE, "js", "hb-docs.js")
    parts = ["{"]
    first = True
    for name in seen:
        if not first:
            parts.append (",")
        first = False
        parts.append ('"%s":"%s"' % (name, seen[name]))
    parts.append ("}")
    body = "".join (parts)

    with open (out_path, "w", encoding = "utf-8") as f:
        f.write (
            "/* Generated by scripts/gen-hb-docs.py from\n"
            " * harfbuzz/docs/harfbuzz-sections.txt.  Do not edit by hand;\n"
            " * re-run the generator against an updated HarfBuzz tree.\n"
            " *\n"
            " * Exposes every public hb_* / HB_* identifier -> docs section\n"
            " * on window so the snippet linkifier can build the right URL. */\n"
            "window.HB_DOC_SYMBOLS = "
        )
        f.write (body)
        f.write (";\n")
    print ("wrote %s (%d symbols)" % (out_path, len (seen)))
    return 0


if __name__ == "__main__":
    sys.exit (main (sys.argv))
